# Generated by Django 2.2.16 on 2022-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='default title'),
            preserve_default=False,
        ),
    ]
